# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'UPX GH Action'
description: 'GitHub Action for UPX, the Ultimate Packer for eXecutables'
author: 'crazy-max'
branding:
  color: 'yellow'
  icon: 'trending-down'

inputs:
  version:
    description: 'UPX version. Example: 3.95'
    default: 'latest'
    required: false
  files:
    description: 'Newline-delimited list of path globs for files to compress'
    required: false
  args:
    description: 'Arguments to pass to UPX'
    required: false
  file:
    deprecationMessage: 'file is deprecated. Please use files input instead.'
    description: 'File to compress'
    required: false
  install-only:
    description: 'Just install upx'
    default: 'false'
    required: false


runs:
  using: 'node20'
  main: 'dist/index.js'
